-- Listar todos los registros por sucursales
CREATE PROCEDURE SP_L_EMPRESA_01
AS
BEGIN
	SELECT * FROM TM_EMPRESA
	WHERE 
	EST = 1
END


--Obtener registro por ID
CREATE PROCEDURE SP_L_EMPRESA_02
@EMP_ID INT
AS
BEGIN
	SELECT * FROM TM_EMPRESA
	WHERE 
	EMP_ID = @EMP_ID
END

--Eliminar registro
CREATE PROCEDURE SP_D_EMPRESA_01
@EMP_ID INT
AS
BEGIN
	UPDATE TM_EMPRESA
	SET
		EST = 0
	WHERE
		EMP_ID = @EMP_ID
END


--Insetar nuevo regitro
CREATE PROCEDURE SP_I_EMPRESA_01
@EMP_NOM VARCHAR (150),
@EMP_RUC VARCHAR(150)
AS
BEGIN
	INSERT INTO TM_EMPRESA
	(EMP_RUC,FECH_CREA,EST)
	VALUES
	(@EMP_RUC, GETDATE(),1)
END

--Actualizar regitro
CREATE PROCEDURE SP_U_EMPRESA_01
@EMP_ID INT,
@EMP_NOM VARCHAR (150),
@EMP_RUC VARCHAR (150)
AS
BEGIN
	UPDATE TM_EMPRESA
	SET
		@EMP_NOM = @EMP_NOM,
		@EMP_RUC = @EMP_RUC
	WHERE
		EMP_ID = @EMP_ID
END