
CREATE PROCEDURE SP_L_MENU_01
@ROL_ID INT
AS
BEGIN
	SELECT TD_MENU.MEND_ID, TD_MENU.MEN_ID, TD_MENU.ROL_ID, 
	TD_MENU.MEND_PERMI, TD_MENU.FECH_CREA, TD_MENU.EST, 
	TM_MENU.MEN_NOM, TM_MENU.MEN_RUTA, TM_MENU.MEN_IDENTI
FROM     TD_MENU INNER JOIN
         TM_MENU ON TD_MENU.MEN_ID = TM_MENU.MEN_ID
WHERE
TD_MENU.ROL_ID = @ROL_ID
END