-- Listar todos los registros por sucursales
ALTER PROCEDURE SP_L_PRODUCTO_01
@SUC_ID INT
AS
BEGIN
	SELECT TM_PRODUCTO.PROD_ID, TM_PRODUCTO.SUC_ID, TM_PRODUCTO.CAT_ID, TM_PRODUCTO.PROD_NOM, 
	TM_PRODUCTO.PROD_DESCRIP, TM_PRODUCTO.UND_ID, TM_PRODUCTO.PROD_PCOMPRA, TM_PRODUCTO.PROD_PVENTA, 
                  TM_PRODUCTO.PROD_STOCK, TM_PRODUCTO.PROD_FECHAVEN, TM_PRODUCTO.PROD_IMG, 
				  TM_PRODUCTO.FECH_CREA, TM_PRODUCTO.EST, TM_CATEGORIA.CAT_NOM, TM_UNIDAD.UND_NOM
FROM     TM_PRODUCTO INNER JOIN
                  TM_CATEGORIA ON TM_PRODUCTO.CAT_ID = TM_CATEGORIA.CAT_ID INNER JOIN
                  TM_UNIDAD ON TM_PRODUCTO.UND_ID = TM_UNIDAD.UND_ID
	WHERE 
	TM_PRODUCTO.SUC_ID = @SUC_ID
	AND TM_PRODUCTO.EST = 1
END


--Obtener registro por ID  
ALTER PROCEDURE SP_L_PRODUCTO_02  
@PROD_ID INT  
AS  
BEGIN  
 SELECT          
TM_PRODUCTO.PROD_ID,   
TM_PRODUCTO.SUC_ID,   
TM_PRODUCTO.CAT_ID,   
TM_PRODUCTO.PROD_NOM,   
TM_PRODUCTO.PROD_DESCRIP,   
TM_PRODUCTO.UND_ID,    
TM_PRODUCTO.PROD_PCOMPRA,   
TM_PRODUCTO.PROD_PVENTA,   
TM_PRODUCTO.PROD_STOCK,   
TM_PRODUCTO.PROD_FECHAVEN,   
TM_PRODUCTO.PROD_IMG,   
TM_PRODUCTO.FECH_CREA,   
TM_PRODUCTO.EST,   
TM_CATEGORIA.CAT_NOM, 
TM_UNIDAD.UND_NOM  
FROM              
TM_PRODUCTO INNER JOIN  
TM_CATEGORIA ON TM_PRODUCTO.CAT_ID = TM_CATEGORIA.CAT_ID INNER JOIN  
TM_UNIDAD ON TM_PRODUCTO.UND_ID = TM_UNIDAD.UND_ID  
 WHERE  
 TM_PRODUCTO.PROD_ID = @PROD_ID  
END

--Eliminar registro
ALTER PROCEDURE SP_D_PRODUCTO_01
@PROD_ID INT
AS
BEGIN
	UPDATE TM_PRODUCTO
	SET
		EST = 0
	WHERE
		PROD_ID = @PROD_ID
END


--Insetar nuevo regitro
ALTER PROCEDURE SP_I_PRODUCTO_01
@SUC_ID INT,
@CAT_ID INT,
@PROD_NOM VARCHAR (150),
@PROD_DESCRIP VARCHAR (150),
@UND_ID INT,
@PROD_PCOMPRA NUMERIC(18,2),
@PROD_PVENTA NUMERIC(18,2),
@PROD_STOCK INT,
@PROD_FECHAVEN DATE,
@PROD_IMG VARCHAR(MAX)
AS
BEGIN
	INSERT INTO TM_PRODUCTO
	(SUC_ID,CAT_ID,PROD_NOM,PROD_DESCRIP,UND_ID,PROD_PCOMPRA,PROD_PVENTA,PROD_STOCK,PROD_FECHAVEN,PROD_IMG,FECH_CREA,EST)
	VALUES
	(@SUC_ID,@CAT_ID,@PROD_NOM,@PROD_DESCRIP,@UND_ID,@PROD_PCOMPRA,@PROD_PVENTA,@PROD_STOCK,@PROD_FECHAVEN,@PROD_IMG, GETDATE(),1)
END

--Actualizar regitro
ALTER PROCEDURE SP_U_PRODUCTO_01
@PROD_ID INT,
@SUC_ID INT,
@CAT_ID INT,
@PROD_NOM VARCHAR (150),
@PROD_DESCRIP VARCHAR (150),
@UND_ID INT,
@PROD_PCOMPRA NUMERIC(18,2),
@PROD_PVENTA NUMERIC(18,2),
@PROD_STOCK INT,
@PROD_FECHAVEN DATE,
@PROD_IMG VARCHAR(MAX)
AS
BEGIN
	UPDATE TM_PRODUCTO
	SET
		SUC_ID = @SUC_ID,
		CAT_ID =  @CAT_ID,
		PROD_NOM = @PROD_NOM,
		PROD_DESCRIP = @PROD_DESCRIP,
		UND_ID = @UND_ID,
		PROD_PCOMPRA = @PROD_PCOMPRA,
		PROD_PVENTA = @PROD_PVENTA,
		PROD_STOCK = @PROD_STOCK,
		PROD_FECHAVEN = @PROD_FECHAVEN,
		PROD_IMG = @PROD_IMG
	WHERE
		PROD_ID = @PROD_ID
END

ALTER PROCEDURE SP_L_PRODUCTO_03    
@CAT_ID INT    
AS    
BEGIN    
SELECT          
TM_PRODUCTO.PROD_ID,   
TM_PRODUCTO.SUC_ID,   
TM_PRODUCTO.CAT_ID,   
TM_PRODUCTO.PROD_NOM,   
TM_PRODUCTO.PROD_DESCRIP,   
TM_PRODUCTO.UND_ID,    
TM_PRODUCTO.PROD_PCOMPRA,   
TM_PRODUCTO.PROD_PVENTA,   
TM_PRODUCTO.PROD_STOCK,   
TM_PRODUCTO.PROD_FECHAVEN,   
TM_PRODUCTO.PROD_IMG,   
TM_PRODUCTO.FECH_CREA,   
TM_PRODUCTO.EST,   
TM_CATEGORIA.CAT_NOM,   
TM_UNIDAD.UND_NOM  
FROM              
TM_PRODUCTO INNER JOIN  
TM_CATEGORIA ON TM_PRODUCTO.CAT_ID = TM_CATEGORIA.CAT_ID INNER JOIN  
TM_UNIDAD ON TM_PRODUCTO.UND_ID = TM_UNIDAD.UND_ID  
 WHERE    
 TM_PRODUCTO. CAT_ID = @CAT_ID    
 AND TM_PRODUCTO.EST=1    
END 


CREATE PROCEDURE SP_L_PRODUCTO_04
@PROD_ID INT
AS
BEGIN
SELECT *FROM 
(
SELECT TM_COMPRA.COMPR_ID, 
CONVERT(VARCHAR, TM_COMPRA.FECH_CREA,103)AS FECH_CREA, 
TD_COMPRA_DETALLE.DETC_CANT, TD_COMPRA_DETALLE.PROD_ID, 
TM_DOCUMENTO.DOC_NOM,
'Compra'AS REGISTRO
FROM     TM_COMPRA INNER JOIN
         TD_COMPRA_DETALLE ON TM_COMPRA.COMPR_ID = TD_COMPRA_DETALLE.COMPR_ID INNER JOIN
         TM_DOCUMENTO ON TM_COMPRA.DOC_ID = TM_DOCUMENTO.DOC_ID
WHERE  TM_COMPRA.EST = 1 
AND TD_COMPRA_DETALLE.PROD_ID = @PROD_ID
UNION ALL
SELECT TM_VENTA.VENT_ID, 
CONVERT(VARCHAR, TM_VENTA.FECH_CREA,103)AS FECH_CREA, 
TD_VENTA_DETALLE.DETV_CANT, TD_VENTA_DETALLE.PROD_ID, 
TM_DOCUMENTO.DOC_NOM,
'Venta'AS REGISTRO
FROM     TM_VENTA INNER JOIN
         TD_VENTA_DETALLE ON TM_VENTA.VENT_ID = TD_VENTA_DETALLE.VENT_ID INNER JOIN
         TM_DOCUMENTO ON TM_VENTA.DOC_ID = TM_DOCUMENTO.DOC_ID
WHERE  TM_VENTA.EST = 1 
AND TD_VENTA_DETALLE.PROD_ID = @PROD_ID
) TABLA
ORDER BY FECH_CREA DESC
END