-- Listar todos los registros por sucursales
CREATE PROCEDURE SP_L_UNIDMED_01
@SUC_ID INT
AS
BEGIN
	SELECT * FROM TM_UNIDMED
	WHERE 
	SUC_ID = @SUC_ID
	AND EST = 1
END


--Obtener registro por ID
CREATE PROCEDURE SP_L_UNIDMED_02
@UND_ID INT
AS
BEGIN
	SELECT * FROM TM_UNIDMED
	WHERE 
	UND_ID = @UND_ID
END

--Eliminar registro
CREATE PROCEDURE SP_D_UNIDMED_01
@UND_ID INT
AS
BEGIN
	UPDATE TM_UNIDMED
	SET
		EST = 0
	WHERE
		UND_ID = @UND_ID
END


--Insetar nuevo regitro
CREATE PROCEDURE SP_I_UNIDMED_01
@SUC_ID INT,
@UND_NOM VARCHAR (150)
AS
BEGIN
	INSERT INTO TM_UNIDMED
	(SUC_ID, UND_NOM, FECH_CREA, EST)
	VALUES
	(@SUC_ID, @UND_NOM, GETDATE(),1)
END

--Actualizar regitro
CREATE PROCEDURE SP_U_UNIDMED_01
@UND_ID INT,
@SUC_ID INT,
@UND_NOM VARCHAR (150)
AS
BEGIN
	UPDATE TM_UNIDMED
	SET
		@SUC_ID = @SUC_ID,
		@UND_NOM = @UND_NOM
	WHERE
		@UND_ID = @UND_ID
END